# Generated by Django 5.0.6 on 2024-05-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='ip_address',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesslog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
