# Generated by Django 5.0.6 on 2024-05-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_accesslog_device_accesslog_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
