# Generated by Django 5.0.6 on 2024-05-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_accesslog_user_alter_accesslog_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('landing_page', 'Landing Page'), ('portfolio', 'Portfólio'), ('agency', 'Agência')], max_length=20)),
                ('template', models.CharField(max_length=100)),
            ],
        ),
    ]
